### ISSUE TITLE
Razeni sloupcu

### ISSUE THREAD

**Issue by xnukes** [ublaboo/datagrid-nette-database-data-source#11]
Ahoj, prosímtě, dotaz. Lze nastavit gridu takovou property aby když radim dle nejakyho sloupce, tak aby se mi radilo pouze ve dvou stavech, nikoliv s tretim stavem default ? priklad na tomto gridu: http://tablesorter.com/docs/ ... kdyz dokola radim jeden sloupec tak jsou jen dva stavy razeni. Tohoto chci docilit. Dikuji ti Pavle :-)

**Comment by paveljanda** [comment]
@xnukes Vše se odehrává v metodě `Column::getSortNext()`. Jednoduché řešení asi nebude.. Ale mohl bys poslat PR, kde bude nějaký setter, který určí, zda se mají v sortu sloupce točit 3 stavy nebo jen 2. :)

**Comment by xnukes** [comment]
@paveljanda Ok, díky za odpověď. Časem tedy udělám PR až v systému upgradujeme ublaboo na poslední verzi :))
