### ISSUE TITLE
Undefined property: NetteDatabaseDataSource::$data_source

### ISSUE THREAD

**Issue by xnukes** [ublaboo/datagrid-nette-database-data-source#3]
Použití addFilterSelect bez použití setCondition funguje skvěle, ale bohužel při setCondition hlasí chybu:
Undefined property: Ublaboo\NetteDatabaseDataSource\NetteDatabaseDataSource::$data_source

**Comment by paveljanda** [comment]
Jakou používáš verzi? Můžeš sem nahrát html log tracy? Takové chování se mi nedaří reprodukovat.

**Comment by xnukes** [comment]
Používám verzi v1.0.5.
Nějak se mi nedaří vytvořit html log tracy, tak jsem ti ulozil stranku s chybou:
[error-tracy.zip](https://github.com/ublaboo/datagrid-nette-database-data-source/files/383512/error-tracy.zip)

**Comment by paveljanda** [comment]
Momentálně je aktuální verze 4.4.7. :)

Máš rozsáhlý projekt? Teoreticky by nemusel činit problém přechod na novou verzi.

**Comment by xnukes** [comment]
Jo aha ty jsi myslel verzi datagridu, tak tu mám 4.4.6, chtel jsem si updatovat na dev verzi kvuli poslednimu vyreseni chyby co jsem psal ale to me zase nepusti kvuli návaznosti na datagrid-nette-database-data-source. Mimochodem teď jsem to updatnul na verzi 4.4.7 ale stejně ta chyba tam je pořád.

**Comment by paveljanda** [comment]
Do masteru datagrid-nette-database-data-source jsem dal novou verzi. Teď je to takto:

Vlastní conditon callback dostane parametrem aktuální sql string, hodnotu filtru a potom aktuální pole parametrů. Callback musí vrátit opět sql string a může upravit pole aktuálních parametrů (& $parameters).

Je to tak vyhovující?

**Comment by xnukes** [comment]
To by mohlo být super, jenže další problém :D updatnul jsem composerem na dev-master a při zavolání callbacku:
->setCondition(function ($query, $value, &$params){
	return $query;
});
vyhodí další chybu: Class 'Ublaboo\NetteDatabaseDataSource\Callback' not found (řádek 147).

**Comment by paveljanda** [comment]
Pardon, master..

**Comment by xnukes** [comment]
Super téměř jsme u finále. Ještě je tam malá chyba, v tom že když dám v té anonymní fci v tom callbacku 3tí parametr jako "&$params" tak to vyhodí chybu, ale když to dám pouze jako $params tak je to v pohodě :) jen bude asi trochu problém pracovat již s poskládaným SQL dotazem, což ale asi se bude moct rozparsovat přes nějakou fci.

**Comment by paveljanda** [comment]
Co je to za chybu?

**Comment by xnukes** [comment]
Kod:
->setCondition(function ($query, $value, &$params) {
	//dump($params);
	return $query;
});
Chyba viz screen:
![image](https://cloud.githubusercontent.com/assets/20656316/17165402/788044a2-53d0-11e6-8085-e9dc4611778c.png)

**Comment by paveljanda** [comment]
M+lo by být fixnuto. Funguje mi například toto:

```php
public function createComponentNDBGrid($name)
{
	$grid = new DataGrid($this, $name);

	$query = "SELECT * FROM ublaboo_example";
	$source = new NetteDatabaseDataSource($this->ndb, $query);

	$grid->setDataSource($source);

	$grid->addColumnText('id', 'Id')
		->setSortable()
		->setFilterText();

	$grid->getFilter('id')
		->setCondition(function($query, $value, &$params) {
			$query .= ' WHERE id LIKE ?';
			$params[] = "%$value%";

			return $query;
		});
}
```
