### ISSUE TITLE
Column 'id' in where clause is ambiguous by action

### ISSUE THREAD

**Issue by pdomkar** [ublaboo/datagrid-nette-database-data-source#5]
Pokud udělám query s joinama více tabulek, které mají položku primární klíč id.
Pri následném volání akce (edit, delete, itemDetail.) se vyhodí chyba SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous

If I do query with JOIN for tables, which have primary key  'id'. And next i call action( edit, delete, itemDetail.). It throw error SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous

**Comment by paveljanda** [comment]
Thanks for your feedback, i will fix that. Can you please write your issue in english? Thanks a lot!

**Comment by paveljanda** [comment]
Can you try to set different primary key? (`DataGrid::setPrimaryKey('user.id')`)

**Comment by pdomkar** [comment]
Yea i try this: `$grid->setPrimaryKey('products.id');`
but it throw error Cannot read an undeclared column 'products'.

**Comment by paveljanda** [comment]
Hmm, i won't do probably anything with that. A have two reasons:
1, Your query should be written solid (try specifying the columns (`user.*, order.id AS order_id`, etc)) and easy to understand
2, The latest Nette\Database won't let me use duplicate columns. User notice `Found duplicate columns in database result set: 'id' (from user, order)` is thrown.
