### ISSUE TITLE
setFilterMultiSelect

### ISSUE THREAD

**Issue by revoke** [ublaboo/datagrid-nette-database-data-source#6]
Tuhle chybu vrací po přidání multifiltru do gridu.
Ublaboo\NetteDatabaseDataSource\NetteDatabaseDataSource::applyFilterMultiSelect(), did you mean applyFilterSelect()

A abych NDDDS rozchodil, musel jsem přidat do Ublaboo\NetteDatabaseDataSource\NetteDatabaseDataSource 
private $queryHelper;

**Comment by paveljanda** [comment]
Mělo by být v pohodě momentálně, testoval jsem.
